### ISSUE TITLE
Help me add tabs dynamically

### ISSUE THREAD

**Issue by Kebap** [Edru2/AdjustableTabWindow#1]
I want to check, if a tab name exists, and if not, add a new tab with said name, for echoing to ECMO later.

It is unclear how to do this, in the original EMCO object, or in the new tabWindow?

Edru says:
> Hm emco:addTab probably won't work. transferEmco just transfers the already established tabs.  And mytabwindow:addTab doesn't create an emco tab. Will have to add this functionality

**Comment by Edru2** [comment]
Yes, this wasn't working before but should work with the new release.
https://github.com/Edru2/AdjustableTabWindow/releases/tag/v1.0.2
Add a new EMCO tab by just using the EMCO function, for example
```lua
myTestEMCO:addTab("Guild")
```
It will transfer the tab automatically to your AdjustableWindow which previously used the transferEMCO function.

Thanks for testing and feel free to report more issues/ideas here on Github :smiley:

**Comment by Edru2** [comment]
With the new release
```lua
Adjustable.TabWindow.convertEMCO(myEMCO)
```
is enough to give your EMCO adjustable tabs but other then that you can continue use your EMCO as usual.

So I'll close this issue because it should be solved. 
We can reopen if there are still problems left.
