### ISSUE TITLE
Single tab windows, do not display content until tab is clicked.

### ISSUE THREAD

**Issue by MorquinDevlar** [Edru2/AdjustableTabWindow#4]
When you create a window with only one tab. The center console does not display anything until the tab is clicked. Even echo'ing something into the center area does nothing.

With more than one tab, everything works fine.

**Comment by Edru2** [comment]
Hello.
Thanks for creating the issue. :)
Can you test if the change I just committed to https://raw.githubusercontent.com/Edru2/AdjustableTabWindow/master/AdjustableTabWindow.xml fixes this bug.

**Comment by MorquinDevlar** [comment]
It looks like it, yes. Thanks a lot.
